version: '2.1'

services:
  db:
    container_name: mysql-lnkr
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
      - MYSQL_DATABASE=microcred
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass@word1
    ports:
      - "3306:3306"
    restart: always
    network_mode: host
    volumes:
      - /opt/microcred/mysqldb:/var/lib/mysql

  tasktrackerbackend:
    image: backend-task-tracker
    build: Backend/TaskTracker
    restart: always
    network_mode: host
    depends_on:
      - db
    ports:
      - 8083:8083
    expose: 
      - 8083

  tasktrackerfrontend:
    image: frontend-task-tracker
    build: FinalFrontEnd
    network_mode: host
    ports: 
      - 4200:4200
    expose:
      - 4200
